sources:
  - name: Kits
    handler:
      openapi:
        endpoint: https://private-8bdaa-solfacilecostorecatalogcoreservice.apiary-mock.com
        source: ./openapi.json # need to consume API OpenAPI json like https://private-8bdaa-solfacilecostorecatalogcoreservice.apiary-mock.com/openapi.json
