serve:
  endpoint: /graphql
  playground: true
sources:
  - name: Kits
    handler:
      openapi:
        endpoint: "{env.KITS_API}"
        source: "{env.KITS_API}/openapi.json"
        operationHeaders:
          Content-Type: application/json
