# fly.toml file generated for graphql-mesh-server on 2023-04-07T11:26:46-03:00

app = "graphql-mesh-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[env]
  KITS_API = "https://private-8bdaa-solfacilecostorecatalogcoreservice.apiary-mock.com"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
